name: Hello World

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Hello World
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Other greetings
        run: |
          echo Hi, there,
          echo I am testing my github actions.
